name: syncly
description: "A To-Do App with Synchronization for all your platforms, with No Data Collection"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 0.0.1+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  
  flutter_spinkit: ^5.2.1
  supabase_flutter: ^2.9.1
  flutter_riverpod: ^2.6.1
  drift_flutter: ^0.2.5
  internet_connection_checker: ^3.0.1
  flutter_local_notifications: ^19.4.0
  intl: ^0.20.2
  sqlite3_flutter_libs: ^0.5.39
  timezone: ^0.10.1
  go_router: ^16.1.0
  stylish_bottom_bar: ^1.1.1
  font_awesome_flutter: ^10.9.0
  table_calendar: ^3.2.0
  timeago: ^3.7.1
  flutter_slidable: ^4.0.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.6.0
  drift_dev: ^2.28.1
  test: ^1.25.15
  mocktail: ^1.0.4



  flutter_lints: ^5.0.0



# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true


  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Zain
      fonts:
        - asset: assets/fonts/zain/Zain-Regular.ttf
        - asset: assets/fonts/zain/Zain-Italic.ttf
          style: italic
        - asset: assets/fonts/zain/Zain-Bold.ttf
          weight: 700
        - asset: assets/fonts/zain/Zain-Light.ttf
          weight: 300
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
